import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "app.lovable.5196d375f0b642d1b73c097cbd42414c",
  appName: "belegmanager",
  webDir: "dist",
  server: {
    url: "https://5196d375-f0b6-42d1-b73c-097cbd42414c.lovableproject.com?forceHideBadge=true",
    cleartext: true,
  },
  ios: {
    scheme: "belegmanager",
  },
  android: {
    // Custom URL scheme handled via AndroidManifest intent-filter (auto-generated by capacitor)
  },
};

export default config;
